"""empty message

Revision ID: 31c121e93432
Revises: b73f4be6b91f
Create Date: 2022-03-02 11:03:39.048202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c121e93432'
down_revision = 'b73f4be6b91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily')
    # ### end Alembic commands ###
