"""empty message

Revision ID: b73f4be6b91f
Revises: 
Create Date: 2022-02-23 11:18:57.480516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73f4be6b91f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=128), nullable=True),
    sa.Column('categories', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_receiver'), 'user', ['receiver'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_receiver'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
